### ISSUE TITLE
"Smite" targeting spells bug with the ribbon keyboard 

### ISSUE THREAD

**Issue by joeljpa** [Cuboideb/angbandroid#1]
Normally the keyboard switches to "*", "'", "5" when you use a regular targeting spell. Press * for the victim and it then gives you the "t" key to lock on. However, for some late game spells where this is not the case, it can get problematic since the keyboard switching doesn't account for that.

Spells like the Mage's "Dimension Door" (or even the Paladin's Single Combat if I recall) where you don't usually target the creatures in range but rather the ground or even creatures normally inaccessible via ranged attacks.  

So to normally cast Dimension Door behind a monster, I've to press "o" to target ground but the ribbon keyboard swaps back to its default layout after that instead of remaining in the target mode layout, forcing me to show the full keyboard to press t manually. Hope I make sense.

**Comment by Cuboideb** [comment]
Fixed in 1.26.1
